language: python

matrix: 
  include: 
    - os: linux
      python: 3.6
    - os: osx
      python: 3.6
      language: generic
install: 
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
before_script:
  - python3 swepy/tests/mock_server.py &
script: 
  - chmod +x .travis/test.sh
  - ./.travis/test.sh
