language: python

matrix: 
  include: 
    - os: linux
      python: 3.7
    - os: osx
      language: generic
      env: TOXENV=py37
install: 
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
script: 
  - chmod +x .travis/test.sh
  - ./.travis/test.sh
