language: python
python:
- '3.6'
install:
- sudo apt-get update
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update conda
- conda info -a
- conda config --add channels conda-forge
- conda env create -f test.yml
- source activate swepy_env
- python setup.py install
before_script:
- python swepy/tests/mock_server.py &
script:
- pytest -v --cov=swepy
after_success:
- codecov
deploy:
  provider: pypi
  user: wino6687
  password:
    secure: BGZ9Rgy2TBH3PjhtKABSHu0reCdvUmkA234AjeX+HMjB+2CfXKUrJdXmgGkPBgfHObwIFfoG/tV9JCA/f7Z+brud8iBb5ReMBIExBhZdmwtiSrmcsVvV8LeC9QnkDdTH68GWPLHlE9xu57wOJkF768MSRl9xuG59T3q1Y+77M5U+mEfI2sTkn8095UCjX89UrOEwKYLu3O56pA7yQ5DF3r62BnT15p6g2lmWOru9jywqbZxpmeI1tCV2knISClHN4FMyJiLr3USR0BQ5T98+aA7qTS4t3tvWeWnaVf4whtIh6vA1bKvW8MT2aaAvhlbmTz4TufMbIsy0l4qY6NjklsgE15m82PaLSYrHhhD/J9tGIKY9Lkm9V5S7efH7e/0eF91rLoHOuL76v8U81ktuF16yuqocj//Zva8OJ+1/eqiub4Uut676vEC0xS2bqmsPWLorpvpwrbAxljn+5r/lRRR0Un4eXPUpOUeHBY2nYfJwiOffslsCiUDeFieVQzNvo3ggmT51acnxgHFcNzkK+IogncKBfUO2Qc3Xtp5ybCXii46uvqgv7SaA9bJp3xxGdGw0d7AQIZEemJikk+JUvibb/96N9CZKMbohqDD8JHFbQdld8icvgJSVEMopyhzOzJG0tDafGB/gLOlCwTBpmtDFWj0IWPlSvFn8MSpoPvM=
  on:
    branch: master
