language: python

matrix: 
  include: 
    - os: linux
      python: 3.6
    - os: osx
      language: generic
install: 
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
script: make test
  # - chmod +x .travis/test.sh
  # - ./.travis/test.sh
