language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # add the needed channels
  - conda config --add channels wino6687
  - conda config --add channels conda-forge
  # create environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION conda-build pandas numpy pytest affine gdal pynco netCDF4 tqdm requests scikit-image cython
  - source activate test-environment
  # install cartopy from git instead of conda
  - pip install git+https://github.com/SciTools/cartopy.git
  #  install swepy with setup.py
  - python setup.py install
  - conda list
before_script:
  # run mock server in order to test scraping
  - python swepy/tests/mock_server.py &
script:
  - pytest -v
after_success:
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash conda/conda_upload.sh
