package:
  name: "flymepy"
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/tedyyan/SWEpy

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - requests
    - cython

about:
  home: https://github.com/tedyyan/SWEpy
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Easy, quick access to CETB files for SWE analysis"

extra:
  recipe-maintainers:
    - tedyyan
