package:
  name: "swepy"
  version: "1.1.5"

requirements:
  host:
    - python
    - setuptools
  build:

  run:
    - python
    - affine
    - gdal
    - pynco
    - pandas
    - jupyter
    - ipykernel
    - requests
    - tqdm
    - scikit-image
    - scikit-learn
    - netCDF4
    - cython
    - cartopy

about:
  home: https://github.com/wino6687/SWEpy
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Easy, quick access to CETB files for SWE analysis"

extra:
  recipe-maintainers:
    - wino6687
