package:
  name: "swepy"
  version: "1.1.5"

source:
  git_rev: v1.1.5
  git_url: https://github.com/wino6687/SWEpy

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - affine
    - gdal
    - pynco
    - pandas
    - jupyter
    - ipykernel
    - requests
    - tqdm
    - scikit-image
    - scikit-learn
    - netCDF4
    - cython

about:
  home: https://github.com/wino6687/SWEpy
  license: LGPLv3
  license_familY: GPL
  license_file: LICENSE
  summary: "Easy, quick access to CETB files for SWE analysis"

extra:
  recipe-maintainers:
    - wino6687
