name: swepy_docs
channels:
- conda-forge
dependencies:
- python=3.7
- pytest-cov
- codecov
- matplotlib
- python=3.6
- pytest
- pandas
- jupyter
- ipykernel
- requests
- tqdm
- pynco
- gdal
- scikit-image
- scikit-learn
- netCDF4