name: swepy_docs
channels:
- conda-forge
dependencies:
- python=3.7
- matplotlib=3.0.3
- rtree=0.8.3
- sphinx=1.8.4
- sphinx_rtd_theme=0.4.3
- m2r=0.2.1
- sphinx-gallery=0.2.0
- tqdm=4.32.2
- fsspec=0.4.3
- numpy=1.17.5