name: swepy_docs
channels:
- conda-forge
dependencies:
- python=3.7
- numpy
- matplotlib=3.0.3
- geopandas=0.4.1
- rtree=0.8.3
- sphinx=1.8.4
- sphinx_rtd_theme=0.4.3
- m2r=0.2.1
- sphinx-gallery=0.2.0
- affine=2.2.2
- tqdm=4.32.2
- xarray=0.12.0
- fsspec=0.4.3
- mapboxgl=0.10.2
- jenkspy=0.1.4